spring.application.name=firstSpringProject

spring.datasource.url=jdbc:mariadb://deeslxapprentice01:3306/todolo
spring.datasource.username=antonio
spring.datasource.password=12345
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
#spring.jpa.show-sql=true
